### ISSUE TITLE
Support for perseus v0.4.0-beta.1 needed in examples/simple

### ISSUE THREAD

**Issue by allen-woods** [arctic-hen7/perseus-size-opt#5]
Please provide a version of `examples/simple` that can be compiled on `perseus v0.4.x` and later.

Current dependencies on `perseus-size-opt v0.1.7` and later cause `cargo` to pull two versions of certain crates when compiling using the current pre-release beta of `perseus` when following Docker Deployment instructions.

Thanks! 😺

**Comment by arctic-hen7** [comment]
I'm actually going to deprecate this plugin entirely with `v0.4.0-beta.2`, which removes `.perseus/`, and thus the need for this plugin. I would advise you leave this plugin entirely out of the `v0.4.x` Docker deployments. The deprecation message will go up once the new version is out (still waiting on a few things from Sycamore).

My reasoning for not updating the plugin is that its whole purpose is to simplify updating `.perseus/Cargo.toml`, which was hidden from the user. With the new architecture, there's just the user's own usual `Cargo.toml`, which means they can more easily control the optimizations they make.

Supporting the first beta version is not really worth doing if the second will deprecate it (since there's no distinction between beta versions in the Perseus docs). That said, I can still add support for the first beta if you want!

**Comment by allen-woods** [comment]
> Supporting the first beta version is not really worth doing if the second will deprecate it (since there's no distinction between beta versions in the Perseus docs). That said, I can still add support for the first beta if you want!

I agree that it wouldn't make sense to resolve this issue as requested when this plugin is being deprecated soon.

My request to make the example available for `0.4.0-beta.1` was simply to standardize existing deployment docs for `docker` across currently available releases.

I'll make adjustments to migrate away from `perseus-size-opt` in 0.4.x and later.
Thanks!

**Comment by arctic-hen7** [comment]
No problem! Note that the next beta of Perseus will come out probably today.
